package core

// this function returns all defined permutations for
// S3 buckets name generation
func GetAllPerms() []string {
	return level_5_perms
}

// this function returns more or less permutations based on given level
// 1 returns less permutations than 6 (1 lower, 5 higher)
func GetPerms(level int) []string {
	if level == 1 {
		return level_1_perms
	} else if level == 2 {
		return level_2_perms
	} else if level == 3 {
		return level_3_perms
	} else if level == 4 {
		return level_4_perms
	} else if level == 5 {
		return level_5_perms
	} else {
		return level_3_perms
	}
}

var level_1_perms []string = []string{"a", "admin", "administration", "api", "aws", "app", "attachments", "assets", "b", "build", "beta", "backup", "backups", "c", "cdn", "cms", "dev", "docs", "documents", "files", "git", "github", "intranet", "login", "es", "static", "packages", "prod", "production", "tmp", "uploads", "web", "www"}

var level_2_perms []string = []string{"a", "admin", "administration", "administrator", "alpha", "assets", "api", "app", "attachments", "aws", "b", "beta", "billing", "blog", "bucket", "backups", "c", "cdn", "cloud", "demo", "dev", "development", "docs", "dev-files", "documents", "exports", "east", "files", "git", "github", "graphql", "info", "init", "live", "login", "media", "net", "photos", "prod", "production", "service", "ssl", "staging", "stage", "static", "support", "uploads", "web", "web-data", "west", "www"}

var level_3_perms []string = []string{"a", "account", "admin", "android", "administration", "administrator", "alpha", "assets", "auto", "api", "app", "ar", "attachments", "aws", "b", "beta", "backups", "billing", "bugs", "build", "br", "c", "cdn", "cloud", "cloudtrail", "club", "com", "corporate", "de", "devops", "demo", "dev", "development", "docs", "documents", "east", "en", "es", "e", "finance", "files", "files-attachments", "fr", "git", "github", "graphql", "ge", "h", "health", "help", "home", "host", "info", "init", "intranet", "it", "kibana", "linux", "live", "local", "login", "mail", "media", "my", "mx", "net", "new", "org", "photos", "pics", "portal", "p", "prod", "production", "service", "ssl", "staging", "stage", "stats", "static", "storage", "support", "tmp", "temp", "uploads", "vpn", "web", "web-data", "west", "www", "mobile"}

var level_4_perms []string = []string{"a", "account", "admin", "administration", "administrator", "alpha", "android", "angular", "ansible", "api", "app", "ar", "assets", "attachments", "auto", "aws", "b", "backgrounds", "backup", "backups", "beta", "betas", "billing", "blog", "bucket", "bugbounty", "bugs", "bugzilla", "build", "bulletins", "business-prod", "c", "ca", "careers", "cdn", "cloud", "cloudtrail", "club", "cluster", "cms", "com", "company", "conference", "confidential", "consultant", "consultants", "consumer", "contact", "content", "contracts", "corporate", "csg", "d", "data", "data-export", "data-exports", "dataset", "de", "demo", "design", "dev", "developer", "developers", "development", "dev-files", "devops", "documents", "dr", "e", "east", "elasticsearch", "en", "engineer", "engineering", "es", "eu", "export", "exports", "files", "files-attachments", "fileserv", "fileserver", "filestore", "finance", "fr", "free", "ge", "general", "git", "github", "h", "health", "helpmedia", "home", "host", "hss", "i", "id", "images", "in", "info", "init", "int", "intranet", "investor", "investors", "io", "ip", "it", "kerberos", "kibana", "linux", "live", "loadbalancer", "local", "localhost", "login", "logos", "logstash", "m", "mail", "marketing", "maven", "media", "mediauploads", "member", "members", "mobile", "mobile-staging", "mvm", "mx", "net", "new", "online", "opensource", "operations", "org", "p", "package", "packages", "partners", "pc", "portal", "presentations", "pro", "prod", "production", "products", "profiles", "project", "projects", "r", "react", "reports", "research", "rest", "ru", "s", "s3", "s3-attachments", "secure", "server", "services", "share", "signature", "sn", "splunk", "srv", "ssl", "stage", "staging", "static", "static-files", "statistics", "stats", "store", "sub", "subversion", "support", "temp", "terraform", "test", "tmp", "training", "ui", "uk", "update", "uploads", "us", "users", "vpn", "web", "web-assets", "webassets", "web-data", "webdata", "website", "website-assets", "websiteassets", "webstatic", "west", "windows", "www"}

var level_5_perms = []string{"a", "account", "admin", "administration", "administrator", "ads", "alpha", "am", "android", "angular", "ansible", "api", "apollo", "app", "ar", "assets", "at", "attach", "attachments", "auto", "avatars", "aws", "awscloudtrail", "aws-logs", "awslogs", "b", "backgrounds", "backup", "backups", "beta", "betas", "billing", "blog", "br", "bucket", "bugbounty", "bugs", "bugzilla", "build", "bulletins", "business-prod", "c", "ca", "careers", "cdn", "cloud", "cloudtrail", "club", "clubs", "cluster", "clusters", "cms", "cn", "com", "company", "conference", "conferencing", "confidential", "consultant", "consultants", "consulting", "consumer", "contact", "content", "contracts", "corporate", "csg", "d", "data", "data-export", "data-exports", "dataset", "datasets", "de", "delivery-app-storage", "deliveryappstorage", "demo", "design", "dev", "devel", "developer", "developers", "development", "dev-files", "devops", "documents", "dr", "e", "east", "elasticsearch", "email-assets", "en", "engineer", "engineering", "es", "eu", "export", "exports", "family", "files", "files-attachments", "fileserv", "fileserver", "filestore", "finance", "fna", "fr", "free", "ge", "gemini", "general", "git", "github", "graphite", "graphql", "h", "health", "helpcenter", "helpcentre", "helpmedia", "home", "host", "hss", "i", "id", "images", "in", "info", "init", "int", "intranet", "invalid", "investor", "investors", "io", "ios", "ip", "it", "iterable", "jp", "kafka", "kbfiles", "kerberos", "keynote", "kibana", "knowledgebase", "la", "linux", "live", "loadbalancer", "local", "localhost", "logexport", "login", "logos", "logstash", "m", "mac", "mail", "maps", "marketing", "matrix", "maven", "media", "mediauploads", "member", "members", "mercurial", "metric", "mobile", "mobile-staging", "mvm", "mx", "my", "net", "new", "of", "onboarding", "online", "opensource", "operations", "opinion", "ops", "org", "p", "package", "packages", "partners", "pc", "pdf-bucket", "photos", "pics", "portal", "ppls", "presentations", "pro", "prod", "production", "products", "profiles", "project", "projects", "public", "pubs-static", "qa", "r", "react", "reports", "research", "reseller", "reserved", "rest", "ru", "s", "s3", "s3-attachments", "secure", "server", "service", "services", "share", "shop", "signature", "sn", "splunk", "spreadsheets", "srv", "ssl", "stage", "staging", "static", "static-files", "statistics", "stats", "store", "sub", "subversion", "support", "support-attachments", "supportdocs", "supportmedia", "supportuploads", "t", "temp", "terraform", "test", "the", "tmp", "training", "uat", "ui", "ui-staging", "uk", "update", "uploads", "us", "user-files", "users", "ux", "video", "vpn", "web", "web-assets", "webassets", "web-data", "webdata", "web-gstatic", "website", "website-assets", "websiteassets", "web-static", "webstatic", "west", "windows", "www", "www-assets"}
